# Rust configuration
rust_toolchain: "1.81.0"

# Local paths on the controller (ensure these directories exist in your playbook folder)
stark_local_dir: "/Users/ruicardoso/bonsol/bonsol/bin/stark"
keypair_local_dir: "/Users/ruicardoso/bonsol/bonsol/bin/stark"

# Remote paths on the node
stark_remote_dir: "/opt/bonsol/stark"
keypair_remote_dir: "/opt/bonsol/keys"
bonsol_dir: "/root/bonsol"
node_config_path: "{{ bonsol_dir }}/Node.toml"

# Bonsol node configuration variables
risc0_image_folder: "/opt/bonsol/risc0_images"
max_input_size_mb: 10
image_download_timeout_secs: 60
input_download_timeout_secs: 60
maximum_concurrent_proofs: 1
max_image_size_mb: 4
image_compression_ttl_hours: 24
env: "dev"
stark_compression_tools_path: "{{ stark_remote_dir }}"
missing_image_strategy: "DownloadAndClaim"

# Repository and endpoint configuration
bonsol_repo: "https://github.com/anagrambuild/bonsol.git"
ingester_grpc_url: "https://your-dragons-mouth-grpc-endpoint"
ingester_grpc_token: "your-grpc-token"
transaction_rpc_url: "https://your-solana-rpc-endpoint"
signer_keypair_path: "{{ keypair_remote_dir }}/your_keypair_file"
